### ISSUE TITLE
It's Not working HTTP

### ISSUE THREAD

**Issue by sahabuddinsk** [horizontalsystems/tor-kit-android#6]
It works only https:// not working http connect, this is a major issue, every onion website are http://...onion not https
please solve this

**Comment by sahabuddinsk** [comment]
Reply please

**Comment by rafaelekol** [comment]
Sorry for late response.
This is internal library for our app Unstoppable Wallet. In order to use Tor for other purposes, you should check [Tor Project](https://github.com/torproject) main repository, or [Tor Android](https://github.com/guardianproject/tor-android) from Guardian Project.
